### ISSUE TITLE
sorry for intruding

### ISSUE THREAD

**Issue by zuaaef** [priyankagaikwad/Assignments#1]
But try this. It will save you hours of headache.
https://cocoapods.org/pods/JTAppleCalendar

**Comment by priyankagaikwad** [comment]
Thank you for the suggestion :)
I want to show the events for that date also in day view, week view and month view. I will try this.

**Comment by zuaaef** [comment]
Sure. I am not sure what you mean by week view,
but you can configure how many rows that is displayed.

You can show 1 row, or 2, 3, or a full 6 rows.
I assume 6 rows = month view
and 1 row = week view? Anyway, glad i can help.
